server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.yourpackage: TRACE


  enabled: true
  test_mode: true
  authorized_phones:
    - "+998909190458"
    - "+998339025262"
    - "+19876543210"


exception:
  handler:
    enabled: true
    resourceNotFoundEnabled: true
    accessDeniedEnabled: true
    invalidInputEnabled: true
