server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.yourpackage: TRACE

twilio:
  account_sid: AC027cb6dfad154e724316794a96ebf8dd
  auth_token: 75820ddd42927f8d58dde50e29046da4
  from_number: +12562425169
  trial_number: +15005550006
  enabled: true
  test_mode: true
  authorized_phones:
    - "+998909190458"
    - "+998339025262"
    - "+19876543210"


exception:
  handler:
    enabled: true
    resourceNotFoundEnabled: true
    accessDeniedEnabled: true
    invalidInputEnabled: true
